// Master Data for InterviewGyani Programmatic SEO -- REAL DATA GENERATED BY AI

export const COUNTRIES = {
    us: {
        name: "United States",
        code: "US",
        currency: "USD",
        price: 49,
        culture_context: "Behavioral & STAR Method",
        interview_style: "In the US, interviewers prioritize the **STAR method** (Situation, Task, Action, Result) and explicit metrics. Candidates are expected to be confident, sell their achievements directly, and demonstrate strong cultural fit.",
        stop_words: ["humble", "maybe", "team effort (without owning impact)"],
        common_feedback: "You need to quantify your impact more. US employers want to hear numbers (e.g., 'improved efficiency by 20%') rather than just tasks."
    },
    uk: {
        name: "United Kingdom",
        code: "UK",
        currency: "USD",
        price: 49,
        culture_context: "Competency & Evidence Based",
        interview_style: "UK interviews heavily focus on **competency-based questions**. Answers should be structured, evidence-backed, and slightly more modest than US styles. 'Banter' or small talk is often a test of cultural fit.",
        stop_words: ["bragging", "overselling", "aggressive"],
        common_feedback: "Your answer felt a bit too aggressive. In the UK, it's better to show quiet confidence and back it up with solid evidence rather than bold claims."
    },
    ca: {
        name: "Canada",
        code: "CA",
        currency: "USD",
        price: 49,
        culture_context: "Technical & Soft Skills Blend",
        interview_style: "Canadian employers look for a balance of **technical prowess and 'Canadian Experience'** (soft skills, politeness, teamwork). Communication clarity is critical, especially for immigrants.",
        stop_words: ["arrogance", "rigidness"],
        common_feedback: "Don't forget the soft skills. Canadian teams value collaboration highly. Mention how you worked with others, not just what you coded."
    },
    au: {
        name: "Australia",
        code: "AU",
        currency: "USD",
        price: 49,
        culture_context: "Straight-talking & Mateship",
        interview_style: "Australian interviews value **authenticity and directness**. They dislike 'waffle' (fluff). You need to be confident but approachable ('mateship culture'). Practical examples win over theoretical ones.",
        stop_words: ["waffle", "buzzwords", "pretentiousness"],
        common_feedback: "Cut the jargon. Australian interviewers prefer plain English and direct answers. If you don't know something, say so."
    }
};

export const ROLES = [
    // --- TECHNOLOGY & ENGINEERING ---
    {
        slug: "software-engineer",
        title: "Software Engineer",
        category: "Tech",
        keywords: ["System Design", "Algorithms", "Scalability", "Clean Code", "CI/CD", "Testing", "Distributed Systems"],
        tech_stack: ["Java", "Python", "AWS", "Docker", "Kubernetes", "SQL"],
        common_failures: [
            "Jumping to code without checking requirements",
            "Ignoring edge cases involved in scale",
            "Not communicating thought process aloud"
        ],
        sample_qa: [
            {
                q: "Tell me about a challenging bug you fixed.",
                a: "Context: Payment race condition. Action: Implemented Redis distributed lock & idempotency keys. Result: 0 duplicate charges, saved 10 support hours/week."
            }
        ]
    },
    {
        slug: "frontend-developer",
        title: "Frontend Developer",
        category: "Tech",
        keywords: ["React/Vue", "Web Vitals", "Accessibility (a11y)", "Responsive Design", "State Management", "CSS Architecture"],
        tech_stack: ["TypeScript", "React", "Next.js", "Tailwind CSS", "Redux", "Jest"],
        common_failures: [
            "Over-engineering simple UI components",
            "Ignoring mobile responsiveness in live coding",
            "Forgetting loading/error states"
        ],
        sample_qa: [
            {
                q: "How do you improve FCP (First Contentful Paint)?",
                a: "I focus on server-side rendering (SSR), optimizing font loading (display: swap), and minimizing critical path CSS. In my last project, these steps cut FCP by 40%."
            }
        ]
    },
    {
        slug: "backend-developer",
        title: "Backend Developer",
        category: "Tech",
        keywords: ["API Design (REST/GraphQL)", "Database Indexing", "Microservices", "Concurrency", "Caching Strategies"],
        tech_stack: ["Node.js", "Go", "PostgreSQL", "Redis", "Kafka", "gRPC"],
        common_failures: [
            "Designing APIs that are chatty or unscalable",
            "Not understanding database ACID properties",
            "Ignoring security best practices (OWASP)"
        ],
        sample_qa: [
            {
                q: "Explain N+1 problem and how to fix it.",
                a: "The N+1 problem occurs when code fetches parent data (1 query) and then individually fetches children (N queries). I fix this using batching or eager loading (e.g., SQL JOINs or DataLoader pattern)."
            }
        ]
    },
    {
        slug: "full-stack-developer",
        title: "Full Stack Developer",
        category: "Tech",
        keywords: ["End-to-End Delivery", "System Architecture", "Database Modeling", "UI/UX Awareness", "DevOps Basics"],
        tech_stack: ["MERN/MEAN Stack", "Next.js", "PostgreSQL", "Docker", "AWS Lambda"],
        common_failures: [
            "Being 'mediocre' at both ends instead of strong at one",
            "Underestimating deployment complexity",
            "Lack of testing across the full stack"
        ],
        sample_qa: [
            {
                q: "How do you handle authentication securely?",
                a: "I use JWTs for stateless auth but ensure they are short-lived. I store refresh tokens in HTTP-only secure cookies to prevent XSS attacks, never in localStorage."
            }
        ]
    },
    {
        slug: "devops-engineer",
        title: "DevOps Engineer",
        category: "Tech",
        keywords: ["Infrastructure as Code", "CI/CD Pipelines", "Observability", "Container Orchestration", "Security Automation"],
        tech_stack: ["Terraform", "Ansible", "Jenkins/GitHub Actions", "Prometheus", "Grafana", "AWS/Azure"],
        common_failures: [
            "Manually configuring servers instead of automation",
            "Ignoring cost optimization in cloud architecture",
            "Treating security as an afterthought"
        ],
        sample_qa: [
            {
                q: "How would you achieve zero-downtime deployment?",
                a: "I use Blue/Green deployment or Canary releases. This routes traffic gradually to the new version, allowing instant rollback via load balancer weight adjustments if error rates spike."
            }
        ]
    },
    {
        slug: "data-scientist",
        title: "Data Scientist",
        category: "Data",
        keywords: ["Machine Learning", "Statistical Modeling", "Feature Engineering", "A/B Testing", "Model Interpretability"],
        tech_stack: ["Python", "Pandas", "Scikit-Learn", "TensorFlow", "SQL", "Jupyter"],
        common_failures: [
            "Focusing only on accuracy, ignoring business value",
            "Overfitting models to training data",
            "Cannot explain model decisions to stakeholders"
        ],
        sample_qa: [
            {
                q: "Explain p-value to a non-technical person.",
                a: "A p-value tells us if a result is likely real or just random luck. A low p-value (like <0.05) means it's very unlikely to be just a lucky coincidence—so the result is statistically significant."
            }
        ]
    },
    {
        slug: "data-analyst",
        title: "Data Analyst",
        category: "Data",
        keywords: ["Data Visualization", "SQL Querying", "Business Intelligence", "Automated Reporting", "Trend Analysis"],
        tech_stack: ["SQL (Advanced)", "Tableau", "PowerBI", "Excel/Sheets", "Python"],
        common_failures: [
            "Pulling numbers without providing insights",
            "Creating cluttered, confusing dashboards",
            "Not verifying data quality/sources"
        ],
        sample_qa: [
            {
                q: "How do you handle missing data?",
                a: "First, I investigate *why* it's missing (MCAR vs MNAR). Then I decide whether to drop rows, impute with mean/median, or use a distinct category like 'Unknown' to avoid biasing the analysis."
            }
        ]
    },
    {
        slug: "qa-engineer",
        title: "QA Engineer",
        category: "Tech",
        keywords: ["Test Automation", "Regression Testing", "Load Testing", "Bug Lifecycle", "Test Strategy"],
        tech_stack: ["Selenium", "Cypress", "Appium", "JIRA", "Postman", "JUnit"],
        common_failures: [
            "Focusing only on happy paths",
            "Writing brittle automation scripts",
            "Poor bug reporting quality"
        ],
        sample_qa: [
            {
                q: "When is it okay not to automate a test?",
                a: "When the feature is unstable/changing rapidly, or if it's a one-off edge case where manual testing is 10x faster than writing/maintaining a script. Automation ROI must be positive."
            }
        ]
    },

    // --- PRODUCT & DESIGN ---
    {
        slug: "product-manager",
        title: "Product Manager",
        category: "Product",
        keywords: ["Product Strategy", "User Research", "Prioritization Frameworks", "Stakeholder Management", "Agile/Scrum"],
        tech_stack: ["JIRA", "Figma", "Amplitude", "Mixpanel", "Notion", "Linear"],
        common_failures: [
            "Solutioning instead of problem definition",
            "Failing to say 'no' to stakeholders",
            "Lack of data-driven decision making"
        ],
        sample_qa: [
            {
                q: "How do you prioritize features?",
                a: "I use the RICE framework (Reach, Impact, Confidence, Effort). For example, I prioritized the 'One-Click Checkout' because it had high Impact and Confidence on revenue, despite medium Effort."
            }
        ]
    },
    {
        slug: "ux-designer",
        title: "UX Designer",
        category: "Design",
        keywords: ["User Empathy", "Wireframing", "Prototyping", "User Testing", "Information Architecture", "Design Systems"],
        tech_stack: ["Figma", "Adobe XD", "Sketch", "Maze", "Miro"],
        common_failures: [
            "Designing for aesthetics over usability",
            "Taking feedback personally",
            "Skipping user research due to 'time constraints'"
        ],
        sample_qa: [
            {
                q: "Walk me through your design process.",
                a: "I follow the Double Diamond process: Discover (Research), Define (Personas/Jobs-to-be-Done), Develop (Ideation/Wireframes), and Deliver (Hi-fi Prototyping & Testing)."
            }
        ]
    },
    {
        slug: "technical-product-manager",
        title: "Technical Product Manager",
        category: "Product",
        keywords: ["API Strategy", "System Architecture", "Developer Experience", "Technical Feasibility", "Release Planning"],
        tech_stack: ["Postman", "SQL", "JIRA", "GitHub", "Datadog"],
        common_failures: [
            "Getting too deep into code instead of strategy",
            "Ignoring the 'business' side of the product",
            "Poor communication with non-technical teams"
        ],
        sample_qa: [
            {
                q: "How do you explain an API to a sales person?",
                a: "I use the 'Waiter' analogy. The API is the waiter taking your order (request) to the kitchen (server) and bringing back the food (response). The customer doesn't need to know how the stove works."
            }
        ]
    },

    // --- BUSINESS & MANAGEMENT ---
    {
        slug: "project-manager",
        title: "Project Manager",
        category: "Business",
        keywords: ["Risk Management", "Scope Creep", "Resource Allocation", "Timeline Planning", "Stakeholder Communication"],
        tech_stack: ["MS Project", "Asana", "JIRA", "Trello", "Excel"],
        common_failures: [
            "Micromanaging the team",
            "Hiding bad news until it's too late",
            "Focusing on process over outcomes"
        ],
        sample_qa: [
            {
                q: "How do you handle scope creep?",
                a: "I document the request and analyze its impact on timeline/budget. Then I present trade-offs to stakeholders: 'We can add X, but it pushes the launch by 2 weeks. Is X critical for launch?'"
            }
        ]
    },
    {
        slug: "business-analyst",
        title: "Business Analyst",
        category: "Business",
        keywords: ["Requirement Gathering", "Process Modeling (BPMN)", "Gap Analysis", "UAT", "Data Interpretation"],
        tech_stack: ["Visio", "Lucidchart", "SQL", "Excel", "JIRA"],
        common_failures: [
            "Making assumptions about user needs",
            "Writing ambiguous requirements",
            "Acting as a passive scribe rather than an analyst"
        ],
        sample_qa: [
            {
                q: "How do you deal with a difficult stakeholder?",
                a: "I focus on active listening to understand their underlying concern, not just their surface demand. I use data to depersonalize decisions and keep communication strictly professional and goal-oriented."
            }
        ]
    },
    {
        slug: "mba-graduate",
        title: "MBA Graduate",
        category: "Business",
        keywords: ["Strategic Thinking", "Market Analysis", "Financial Modeling", "Operational Efficiency", "Leadership Potential"],
        tech_stack: ["Excel (Advanced Modeling)", "PowerPoint", "Bloomberg", "Salesforce"],
        common_failures: [
            "Being too theoretical / 'Academic'",
            "Using jargon without substance",
            "Lack of humility when working with operational teams"
        ],
        sample_qa: [
            {
                q: "Tell me about a time you led without authority.",
                a: "During a cross-functional initiative, I couldn't order engineering to prioritize my request. Instead, I built a business case showing the revenue potential, which naturally aligned their incentives with mine."
            }
        ]
    },
    {
        slug: "marketing-manager",
        title: "Marketing Manager",
        category: "Marketing",
        keywords: ["Go-to-Market Strategy", "Brand Positioning", "CAC/LTV Analysis", "Digital Marketing", "Content Strategy"],
        tech_stack: ["HubSpot", "Google Analytics", "Salesforce", "Marketo", "Canva"],
        common_failures: [
            "Focusing on vanity metrics (likes) over revenue",
            "Lack of alignment with Sales team",
            "Inconsistent brand messaging"
        ],
        sample_qa: [
            {
                q: "How do you measure campaign success?",
                a: "I look beyond clicks. I track conversion rate, Cost Per Acquisition (CPA), and ultimately Return on Ad Spend (ROAS). If a campaign brings leads but they don't close, it's a failure."
            }
        ]
    },
    {
        slug: "sales-executive",
        title: "Sales Executive",
        category: "Sales",
        keywords: ["Prospecting", "Consultative Selling", "Negotiation", "Pipeline Management", "Closing Techniques"],
        tech_stack: ["Salesforce", "LinkedIn Sales Nav", "Outreach.io", "ZoomInfo"],
        common_failures: [
            "Talking more than listening",
            "Failing to follow up effectively",
            "Not qualifying leads (chasing bad deals)"
        ],
        sample_qa: [
            {
                q: "Sell me this pen.",
                a: "I wouldn't list features. I'd ask: 'When was the last time you needed to sign something important?' I identify the need (pain) first, then position the pen as the solution."
            }
        ]
    },
    {
        slug: "customer-success-manager",
        title: "Customer Success Manager",
        category: "Sales",
        keywords: ["Retention Strategy", "Churn Reduction", "Up-selling", "Customer Onboarding", "Relationship Building"],
        tech_stack: ["Gainsight", "Zendesk", "Salesforce", "Intercom"],
        common_failures: [
            "Being reactive (support) instead of proactive (success)",
            "Failing to identify churn risks early",
            "Not demonstrating ongoing value to the client"
        ],
        sample_qa: [
            {
                q: "How do you handle a customer who wants to cancel?",
                a: "I first seek to understand the 'why'—is it price, value, or a specific blocker? I validate their concern, then propose a tailored success plan to bridge the gap, or offer a temporary downgrade if budget is the issue."
            }
        ]
    },

    // --- CYBERSECURITY & IT ---
    {
        slug: "cybersecurity-analyst",
        title: "Cybersecurity Analyst",
        category: "Tech",
        keywords: ["Threat Intelligence", "Incident Response", "Vulnerability Assessment", "SIEM", "Penetration Testing"],
        tech_stack: ["Splunk", "wireshark", "Metasploit", "Nmap", "CrowdStrike"],
        common_failures: [
            "False positives overload",
            "Poor documentation of incidents",
            "Focusing on tools rather than threat actors"
        ],
        sample_qa: [
            {
                q: "Explain the difference between encoding, encryption, and hashing.",
                a: "Encoding is for data usability (reversible). Encryption is for confidentiality (reversible with key). Hashing is for integrity (one-way, irreversible)."
            }
        ]
    },
    {
        slug: "network-engineer",
        title: "Network Engineer",
        category: "Tech",
        keywords: ["Routing Protocols (BGP/OSPF)", "Subnetting", "VPN Configuration", "Firewall Rules", "Network Topology"],
        tech_stack: ["Cisco IOS", "Juniper", "Wireshark", "SolarWinds", "Palo Alto Networks"],
        common_failures: [
            "Misconfiguring access control lists (ACLs)",
            "Lack of redundancy in design",
            "Poor cable management/documentation"
        ],
        sample_qa: [
            {
                q: "What happens when you type google.com?",
                a: "DNS Resolution -> TCP Handshake -> TLS Handshake -> HTTP Request -> Server Response -> Browser Rendering. I can dive deep into any specific step."
            }
        ]
    },
    {
        slug: "cloud-architect",
        title: "Cloud Architect",
        category: "Tech",
        keywords: ["Cloud Migration", "Serverless Architecture", "Cost Optimization", "Disaster Recovery", "Cloud Security"],
        tech_stack: ["AWS Well-Architected Framework", "Azure Solutions", "GCP", "Kubernetes", "Terraform"],
        common_failures: [
            "Over-provisioning resources (cost waste)",
            "Designing single points of failure",
            "Ignoring data sovereignty/compliance"
        ],
        sample_qa: [
            {
                q: "Monolith vs Microservices - how do you choose?",
                a: "Monolith first. It's easier to develop/deploy. I only move to microservices when the organizational complexity (team size) or scaling requirements specifically demand independent deployability."
            }
        ]
    },

    // --- EMERGING ROLES ---
    {
        slug: "ai-engineer",
        title: "AI Engineer",
        category: "Tech",
        keywords: ["LLM Fine-tuning", "RAG Pipelines", "Prompt Engineering", "Vector Databases", "Model Evaluation"],
        tech_stack: ["OpenAI API", "HuggingFace", "LangChain", "Pinecone", "Python"],
        common_failures: [
            "Hallucination management",
            "Ignoring inference costs/latency",
            "Lack of proper evaluation benchmarks (evals)"
        ],
        sample_qa: [
            {
                q: "How do you reduce hallucinations in RAG?",
                a: "I improve chunking strategy, increase retrieval relevance (hybrid search), and add a verification step where a second model checks if the answer is grounded in the retrieved context."
            }
        ]
    },
    {
        slug: "scrum-master",
        title: "Scrum Master",
        category: "Process",
        keywords: ["Agile Ceremonies", "Burndown Charts", "Blocker Removal", "Servant Leadership", "Sprint Planning"],
        tech_stack: ["JIRA", "Confluence", "Miro", "Monday.com"],
        common_failures: [
            "Acting as a boss/manager instead of a facilitator",
            "Being rigid about process over people",
            "Failing to protect the team from external noise"
        ],
        sample_qa: [
            {
                q: "The team is consistently failing sprint goals. What do you do?",
                a: "I bring it to the Retrospective. We analyze root causes—are we overcommitting? Are stories vague? Are external interruptions high? We then agree on one specific experiment to fix it next sprint."
            }
        ]
    }
];

export const INTENTS = {
    "mock-interview": {
        titleTemplate: "AI Mock Interview for {ROLE} in {COUNTRY}",
        descriptionTemplate: "Practice with our AI interviewer. Get instant feedback on your {ROLE} answers tailored for {COUNTRY} employers.",
        type: "interactive"
    },
    "interview-questions": {
        titleTemplate: "Top {ROLE} Interview Questions {COUNTRY} (with AI Answers)",
        descriptionTemplate: "Don't just memorize list. See how to answer top {ROLE} questions specifically for the {COUNTRY} job market.",
        type: "content"
    },
    "interview-feedback": {
        titleTemplate: "Get Feedback on your {ROLE} Interview Answers ({COUNTRY})",
        descriptionTemplate: "Paste or speak your answer. Our AI scores it against {COUNTRY} hiring standards for {ROLE} positions.",
        type: "tool"
    },
    "confidence-practice": {
        titleTemplate: "Interview Confidence Training for {ROLE} ({COUNTRY})",
        descriptionTemplate: "Overcome interview anxiety. Safe, private practice space for {ROLE} candidates in {COUNTRY}.",
        type: "coaching"
    }
};
