export const coverLetterTemplates = {
  // Classic Professional Design
  classic: {
    name: "Classic Professional",
    category: "General",
    premium: false,
    description: "Timeless and elegant with traditional formatting - perfect for corporate roles.",
    defaultData: {
      enabled: true,
      name: "",
      email: "",
      phone: "",
      location: "",
      recipient: "Dear Hiring Manager",
      jobTitle: "",
      company: "",
      intro: "",
      body: "",
      closing: "",
    },
    styles: {
      fontFamily: "'Arial', sans-serif",
      fontSize: "12pt",
      lineHeight: "1.5",
      letterSpacing: "0.1px",
      maxWidth: "800px",
      padding: "40px",
      border: "none",
      borderRadius: "0",
      boxShadow: "none",
      divider: "1px solid #e5e7eb",
      useIcons: false,
      colors: {
        primary: "#2c3e50",
        secondary: "#7f8c8d",
        accent: "#3498db",
        text: "#34495e",
        background: "#ffffff",
      },
    },
    layout: { headerStyle: "compact" },
  },

  // Modern Minimalist Design
  sleek: {
    name: "Modern Professional",
    category: "General",
    premium: false,
    description: "Clean professional design with navy accents - ideal for tech and business professionals.",
    defaultData: {
      enabled: true,
      name: "",
      email: "",
      phone: "",
      location: "",
      recipient: "Dear Hiring Manager",
      jobTitle: "",
      company: "",
      intro: "",
      body: "",
      closing: "",
    },
    styles: {
      fontFamily: "'Roboto', sans-serif",
      fontSize: "11pt",
      lineHeight: "1.7",
      letterSpacing: "0.2px",
      maxWidth: "780px",
      padding: "35px",
      border: "none",
      borderRadius: "8px",
      boxShadow: "0 4px 20px rgba(0, 0, 0, 0.05)",
      divider: "1px solid #e5e7eb",
      useIcons: true,
      colors: {
        primary: "#1e3a8a",
        secondary: "#64748b",
        accent: "#3b82f6",
        text: "#1f2937",
        background: "#ffffff",
      },
    },
    layout: { headerStyle: "full-width" },
  },

  // Executive Professional Design
  executive: {
    name: "Executive Bold",
    category: "Leadership",
    premium: true,
    description: "Bold and authoritative with serif fonts - designed for C-level executives and senior leaders.",
    defaultData: {
      enabled: true,
      name: "",
      email: "",
      phone: "",
      location: "",
      recipient: "Dear Hiring Manager",
      jobTitle: "",
      company: "",
      intro: "",
      body: "",
      closing: "",
    },
    styles: {
      fontFamily: "'Georgia', serif",
      fontSize: "12pt",
      lineHeight: "1.6",
      letterSpacing: "0.15px",
      maxWidth: "900px",
      padding: "50px",
      border: "2px solid #1f2937",
      borderRadius: "0",
      boxShadow: "0 10px 40px rgba(0, 0, 0, 0.1)",
      divider: "3px solid #1f2937",
      useIcons: false,
      colors: {
        primary: "#1f2937",
        secondary: "#374151",
        accent: "#3b82f6",
        text: "#111827",
        background: "#ffffff",
      },
    },
    layout: { headerStyle: "executive" },
  },

  // Minimalist Modern Design
  minimalist: {
    name: "Minimalist Clean",
    category: "Modern",
    premium: false,
    description: "Ultra-clean design with side accent bar - perfect for designers and creative professionals.",
    defaultData: {
      enabled: true,
      name: "",
      email: "",
      phone: "",
      location: "",
      recipient: "Dear Hiring Manager",
      jobTitle: "",
      company: "",
      intro: "",
      body: "",
      closing: "",
    },
    styles: {
      fontFamily: "'Inter', sans-serif",
      fontSize: "11pt",
      lineHeight: "1.8",
      letterSpacing: "0.3px",
      maxWidth: "750px",
      padding: "60px",
      border: "none",
      borderRadius: "0",
      boxShadow: "none",
      divider: "1px solid #f3f4f6",
      useIcons: false,
      colors: {
        primary: "#111827",
        secondary: "#6b7280",
        accent: "#3b82f6",
        text: "#374151",
        background: "#ffffff",
      },
    },
    layout: { headerStyle: "minimal" },
  },

  // Infographic Style Design
  infographic: {
    name: "Creative Professional",
    category: "Creative",
    premium: true,
    description: "Clean left-accent design with professional typography - ideal for creative and marketing roles.",
    defaultData: {
      enabled: true,
      name: "",
      email: "",
      phone: "",
      location: "",
      recipient: "Dear Hiring Manager",
      jobTitle: "",
      company: "",
      intro: "",
      body: "",
      closing: "",
    },
    styles: {
      fontFamily: "'Poppins', sans-serif",
      fontSize: "11pt",
      lineHeight: "1.7",
      letterSpacing: "0.2px",
      maxWidth: "850px",
      padding: "45px",
      border: "none",
      borderRadius: "12px",
      boxShadow: "0 8px 32px rgba(0, 0, 0, 0.08)",
      divider: "2px solid #e5e7eb",
      useIcons: true,
      colors: {
        primary: "#1e40af",
        secondary: "#64748b",
        accent: "#06b6d4",
        text: "#1e293b",
        background: "#ffffff",
      },
    },
    layout: { headerStyle: "modern" },
  },

  // Tech-Focused Design
  innovate: {
    name: "Tech Professional",
    category: "Technology",
    premium: true,
    description: "Clean professional design with modern styling - perfect for software developers and engineers.",
    defaultData: {
      enabled: true,
      name: "",
      email: "",
      phone: "",
      location: "",
      recipient: "Dear Hiring Manager",
      jobTitle: "",
      company: "",
      intro: "",
      body: "",
      closing: "",
    },
    styles: {
      fontFamily: "'Fira Code', monospace",
      fontSize: "10pt",
      lineHeight: "1.65",
      letterSpacing: "0.3px",
      maxWidth: "820px",
      padding: "40px",
      border: "none",
      borderRadius: "10px",
      boxShadow: "0 6px 25px rgba(0, 0, 0, 0.06)",
      divider: "1px solid #dbeafe",
      useIcons: true,
      colors: {
        primary: "#2f4f4f",
        secondary: "#5f7f7f",
        accent: "#4ecdc4",
        text: "#1f1f1f",
        background: "#ffffff",
      },
    },
    layout: { headerStyle: "innovate" },
  },

  // Creative Professional Design
  inspire: {
    name: "Creative Elegant",
    category: "Creative",
    premium: true,
    description: "Elegant left-accent design with refined typography - perfect for artists and designers.",
    defaultData: {
      enabled: true,
      name: "",
      email: "",
      phone: "",
      location: "",
      recipient: "Dear Hiring Manager",
      jobTitle: "",
      company: "",
      intro: "",
      body: "",
      closing: "",
    },
    styles: {
      fontFamily: "'Playfair Display', serif",
      fontSize: "11pt",
      lineHeight: "1.8",
      letterSpacing: "0.15px",
      maxWidth: "800px",
      padding: "45px",
      border: "none",
      borderRadius: "12px",
      boxShadow: "0 5px 22px rgba(0, 0, 0, 0.04)",
      divider: "1px dashed #b76e79",
      useIcons: true,
      colors: {
        primary: "#4b2e39",
        secondary: "#6b4e56",
        accent: "#b76e79",
        text: "#333333",
        background: "linear-gradient(180deg, #fdfdfd 0%, #f5f5f5 100%)",
      },
    },
    layout: { headerStyle: "default" },
  },

  // Leadership-Oriented Design
  summit: {
    name: "Modern Leadership",
    category: "Leadership",
    premium: true,
    description: "Sophisticated professional design with clean layout - perfect for senior managers and VPs.",
    defaultData: {
      enabled: true,
      name: "",
      email: "",
      phone: "",
      location: "",
      recipient: "Dear Hiring Manager",
      jobTitle: "",
      company: "",
      intro: "",
      body: "",
      closing: "",
    },
    styles: {
      fontFamily: "'Lora', serif",
      fontSize: "11.5pt",
      lineHeight: "1.75",
      letterSpacing: "0.25px",
      maxWidth: "850px",
      padding: "50px",
      border: "none",
      borderRadius: "0",
      boxShadow: "0 8px 30px rgba(0, 0, 0, 0.08)",
      divider: "2px solid #718096",
      useIcons: false,
      colors: {
        primary: "#2d3748",
        secondary: "#718096",
        accent: "#3182ce",
        text: "#1a202c",
        background: "#ffffff",
      },
    },
    layout: { headerStyle: "full-width" },
  },

  // Startup Modern Design
  startup: {
    name: "Dynamic Professional",
    category: "Modern",
    premium: false,
    description: "Clean modern design with professional accents - ideal for startups and growth companies.",
    defaultData: {
      enabled: true,
      name: "",
      email: "",
      phone: "",
      location: "",
      recipient: "Dear Hiring Manager",
      jobTitle: "",
      company: "",
      intro: "",
      body: "",
      closing: "",
    },
    styles: {
      fontFamily: "'Montserrat', sans-serif",
      fontSize: "11pt",
      lineHeight: "1.6",
      letterSpacing: "0.2px",
      maxWidth: "800px",
      padding: "40px",
      border: "none",
      borderRadius: "16px",
      boxShadow: "0 12px 40px rgba(0, 0, 0, 0.1)",
      divider: "2px solid #f59e0b",
      useIcons: true,
      colors: {
        primary: "#1f2937",
        secondary: "#6b7280",
        accent: "#f59e0b",
        text: "#374151",
        background: "#ffffff",
      },
    },
    layout: { headerStyle: "startup" },
  },

  // Healthcare Professional Design
  healthcare: {
    name: "Professional Healthcare",
    category: "Professional",
    premium: false,
    description: "Clean and trustworthy professional design - perfect for healthcare and medical professionals.",
    defaultData: {
      enabled: true,
      name: "",
      email: "",
      phone: "",
      location: "",
      recipient: "Dear Hiring Manager",
      jobTitle: "",
      company: "",
      intro: "",
      body: "",
      closing: "",
    },
    styles: {
      fontFamily: "'Merriweather', serif",
      fontSize: "11pt",
      lineHeight: "1.7",
      letterSpacing: "0.15px",
      maxWidth: "800px",
      padding: "45px",
      border: "none",
      borderRadius: "8px",
      boxShadow: "0 6px 25px rgba(0, 0, 0, 0.06)",
      divider: "2px solid #10b981",
      useIcons: false,
      colors: {
        primary: "#065f46",
        secondary: "#047857",
        accent: "#10b981",
        text: "#064e3b",
        background: "#ffffff",
      },
    },
    layout: { headerStyle: "healthcare" },
  },
};