export const jobSpecificTemplates = {
  // IT Fresher - Modern Tech Stack Layout
  it_fresher: {
    name: "IT Fresher - Modern",
    previewImage: "/templates/previews/it_fresher.png",
    category: "Job-Specific",
    layout: {
      type: "sidebar",
      headerType: "modern-tech",
      sectionsOrder: ["personal", "summary", "skills", "projects", "education", "certifications", "languages", "customSections"],
      sidebarSections: ["personal.photo", "skills", "certifications"],
      mainSections: ["summary", "projects", "education"],
      showIcons: true,
      sidebar: "left",
      sidebarWidth: "35%",
      sectionCard: true,
      sectionDividers: false,
    },
    styles: {
      fontFamily: "'Inter', 'Segoe UI', sans-serif",
      fontSize: "10pt",
      lineHeight: "1.5",
      borderRadius: "10px",
      photo: {
        shape: "circle",
        size: "100px",
        border: "3px solid #374151",
        shadow: "0 4px 12px rgba(55, 65, 81, 0.2)",
      },
      colors: {
        primary: "#1f2937",
        secondary: "#6b7280",
        accent: "#374151",
        text: "#111827",
        background: "#ffffff",
        sidebar: "#f9fafb",
        headerGradient: "linear-gradient(135deg, #1f2937 0%, #374151 100%)",
        cardBg: "#f9fafb",
        border: "#e5e7eb",
      },
      icons: {
        skills: "⚡",
        projects: "🚀", 
        education: "🎓",
        certifications: "🏆",
        languages: "🌐"
      }
    },
 
    defaultData: {
      personal: {
        name: "Aarav Sharma",
        email: "aarav.sharma@example.com",
        phone: "+91 98765 43210",
        address: "Bangalore, Karnataka, India",
        dateOfBirth: "",
        gender: "",
        maritalStatus: "",
      },
      summary: "Motivated B.Tech graduate with strong programming skills in Java and Python, seeking an entry-level software development role. Passionate about building innovative solutions and eager to contribute to a dynamic IT team.",
      skills: ["Java", "Python", "SQL", "HTML/CSS", "JavaScript", "Git", "Problem Solving"],
      projects: [
        {
          title: "E-Commerce Website",
          description: "Developed a full-stack e-commerce platform using React, Node.js, and MongoDB. Implemented user authentication and payment gateway integration.",
          startDate: "Jan 2023",
          endDate: "Apr 2023",
        },
      ],
      experience: [],
      education: [
        {
          degree: "B.Tech in Computer Science",
          institution: "NIT Karnataka",
          startDate: "2019",
          endDate: "2023",
          grade: "CGPA: 8.5/10",
        },
      ],
      certifications: [
        {
          title: "Java SE 8 Programmer Certification",
          issuer: "Oracle",
          date: "May 2023",
        },
      ],
      languages: ["English (Fluent)", "Hindi (Native)"],
      achievements: ["Winner, College Coding Hackathon 2022"],
      references: [],
    },
  },

  // Bank PO - Professional Executive Layout
  bank_po: {
    name: "Bank PO - Executive",
    previewImage: "/templates/previews/bank_po.png", 
    category: "Job-Specific",
    layout: {
      type: "executive",
      headerType: "executive-banner",
      sectionsOrder: ["personal", "summary", "experience", "education", "skills", "certifications", "achievements", "languages", "customSections"],
      sidebarSections: [],
      mainSections: ["summary", "experience", "education", "skills", "certifications", "achievements"],
      showIcons: false,
      columns: 1,
      sectionCard: false,
      sectionDividers: true,
    },
    styles: {
      fontFamily: "'Crimson Text', 'Times New Roman', serif",
      fontSize: "11pt",
      lineHeight: "1.6",
      borderRadius: "8px",
      photo: {
        shape: "rounded",
        size: "90px",
        border: "2px solid #111827",
        shadow: "0 3px 10px rgba(30, 58, 138, 0.2)",
      },
      colors: {
        primary: "#111827",
        secondary: "#6b7280",
        accent: "#374151",
        text: "#111827",
        background: "#ffffff",
        sidebar: "#f9fafb",
        headerGradient: "linear-gradient(135deg, #111827 0%, #374151 100%)",
        cardBg: "#f9fafb",
        border: "#e5e7eb",
      },
      icons: {
        experience: "💼",
        education: "🎓", 
        skills: "⭐",
        certifications: "📜",
        achievements: "🏆"
      }
    },
   
    defaultData: {
      personal: {
        name: "Priya Gupta",
        email: "priya.gupta@example.com",
        phone: "+91 87654 32109",
        address: "Mumbai, Maharashtra, India",
        dateOfBirth: "",
        gender: "",
        maritalStatus: "",
      },
      summary: "Detail-oriented commerce graduate with internship experience in banking operations. Strong analytical skills and a proven track record in customer service, aiming to excel as a Probationary Officer in a reputed bank.",
      skills: ["Financial Analysis", "Customer Service", "MS Excel", "Accounting", "Team Collaboration"],
      projects: [],
      experience: [
        {
          title: "Banking Intern",
          company: "HDFC Bank",
          startDate: "Jun 2022",
          endDate: "Dec 2022",
          description: "Assisted in account management, processed transactions, and supported customer queries, improving branch efficiency by 15%.",
        },
      ],
      education: [
        {
          degree: "B.Com (Banking & Finance)",
          institution: "University of Mumbai",
          startDate: "2019",
          endDate: "2022",
          grade: "Percentage: 78%",
        },
      ],
      certifications: [
        {
          title: "Certified Banking Associate",
          issuer: "US Institute of Banking & Finance",
          date: "Jan 2023",
        },
      ],
      languages: ["English (Fluent)", "Hindi (Fluent)", "Marathi (Native)"],
      achievements: ["Ranked Top 5% in Bank PO Mock Tests", "Best Intern Award, HDFC Bank, 2022"],
      references: [
        {
          name: "Mr. Sanjay Patel",
          position: "Branch Manager",
          company: "HDFC Bank",
          contact: "sanjay.patel@hdfcbank.com | +91 98765 43212",
        },
      ],
    },
  },

  // Government Job - Official Format
  government_job: {
    name: "Government - Official",
    previewImage: "/templates/previews/government_job.png",
    category: "Job-Specific", 
    layout: {
      type: "formal",
      headerType: "official-header",
      sectionsOrder: ["personal", "summary", "experience", "education", "skills", "certifications", "references", "languages", "customSections"],
      sidebarSections: [],
      mainSections: ["summary", "experience", "education", "skills", "certifications", "references"],
      showIcons: false,
      columns: 1,
      sectionCard: false,
      sectionDividers: true,
    },
    styles: {
      fontFamily: "'Source Sans Pro', Arial, sans-serif",
      fontSize: "11pt",
      lineHeight: "1.6",
      borderRadius: "6px",
      photo: {
        shape: "rounded",
        size: "85px",
        border: "2px solid #1f2937",
        shadow: "0 2px 8px rgba(23, 37, 84, 0.15)",
      },
      colors: {
        primary: "#1f2937",
        secondary: "#6b7280",
        accent: "#374151",
        text: "#111827",
        background: "#ffffff",
        sidebar: "#ffffff",
        headerGradient: "linear-gradient(135deg, #1f2937 0%, #6b7280 100%)",
        cardBg: "#f9fafb",
        border: "#d1d5db",
      },
      icons: {
        experience: "🏛️",
        education: "📚",
        skills: "🛠️", 
        certifications: "📋",
        references: "📝"
      }
    },
        
    defaultData: {
      personal: {
        name: "Rahul Verma",
        email: "rahul.verma@example.com",
        phone: "+91 76543 21098",
        address: "New Delhi, India",
        dateOfBirth: "",
        gender: "",
        maritalStatus: "",
      },
      summary: "Dedicated professional with 2 years of administrative experience and a strong academic background, seeking a government position to serve the public with integrity and efficiency.",
      skills: ["Public Administration", "Record Keeping", "MS Office", "Regulatory Compliance", "Communication"],
      projects: [],
      experience: [
        {
          title: "Administrative Assistant",
          company: "Delhi Municipal Corporation",
          startDate: "Mar 2021",
          endDate: "Feb 2023",
          description: "Managed records, coordinated public inquiries, and assisted in policy documentation, ensuring compliance with government regulations.",
        },
      ],
      education: [
        {
          degree: "B.A. in Public Administration",
          institution: "University of Delhi",
          startDate: "2017",
          endDate: "2020",
          grade: "Percentage: 72%",
        },
      ],
      certifications: [
        {
          title: "Certificate in Public Policy",
          issuer: "IGNOU",
          date: "Dec 2022",
        },
      ],
      languages: ["English (Fluent)", "Hindi (Native)"],
      achievements: ["Employee of the Month, Delhi Municipal Corporation, Jan 2022"],
      references: [
        {
          name: "Mr. Anil Kumar",
          position: "Supervisor",
          company: "Delhi Municipal Corporation",
          contact: "anil.kumar@example.com | +91 98765 43211",
        },
      ],
    },
  },

  // IT Fresher (Left Sidebar)
  it_fresher_left: {
    name: "IT Fresher (Left Sidebar)",
    previewImage: "/templates/previews/it_fresher_left.png",
    category: "Job-Specific",
    premium: false,
    layout: {
      sectionsOrder: ["personal", "summary", "skills", "projects", "education", "certifications", "languages", "customSections"],
      sidebarSections: ["personal.photo", "skills", "languages"],
      mainSections: ["personal", "summary", "projects", "education", "certifications"],
      showIcons: true,
      columns: 2,
      sidebar: "left",
      sidebarWidth: "30%",
    },
    styles: {
      fontFamily: "'Poppins', sans-serif",
      fontSize: "11pt",
      lineHeight: "1.5",
      colors: {
        primary: "#1f2937",
        secondary: "#6b7280",
        accent: "#374151",
        text: "#111827",
        background: "#ffffff",
        sidebar: "#f9fafb",
      },
      photo: {
        shape: "circle",
        size: "110px",
        border: "2px solid #374151",
      },
    },
    defaultData: {
      personal: {
        name: "Aarav Sharma",
        email: "aarav.sharma@example.com",
        phone: "+91 98765 43210",
        address: "Bangalore, Karnataka, India",
        dateOfBirth: "15 May 2000",
        gender: "male",
        maritalStatus: "single",
        nationality: "US",
        linkedin: "linkedin.com/in/aaravsharma",
        github: "github.com/aaravsharma",
        photo: "",
      },
      summary: "Enthusiastic B.Tech graduate specializing in full-stack development, eager to contribute to innovative IT solutions.",
      skills: [
        "Java",
        "Python",
        "JavaScript",
        "React.js",
        "Node.js",
        "SQL",
        "HTML5",
        "CSS3",
        "Git",
        "REST APIs",
        "Problem Solving",
        "Team Collaboration",
      ],
      projects: [
        {
          title: "E-Commerce Platform",
          description: "Built a responsive e-commerce site with React, Node.js, and MongoDB, featuring user authentication and payment integration.",
          startDate: "Jan 2023",
          endDate: "Apr 2023",
          technologies: "React, Node.js, MongoDB, Express",
        },
        {
          title: "Task Management App",
          description: "Developed a task tracker with Python Flask and SQLite, deployed on Heroku.",
          startDate: "Sep 2022",
          endDate: "Dec 2022",
          technologies: "Python, Flask, SQLite",
        },
      ],
      experience: [],
      education: [
        {
          degree: "B.Tech in Computer Science",
          institution: "NIT Karnataka",
          startDate: "2019",
          endDate: "2023",
          grade: "CGPA: 8.5/10",
        },
        {
          degree: "Class XII (CBSE)",
          institution: "Delhi Public School, Bangalore",
          startDate: "2017",
          endDate: "2019",
          grade: "Percentage: 92%",
        },
      ],
      certifications: [
        { title: "Java SE 8 Programmer", issuer: "Oracle", date: "May 2023" },
        { title: "AWS Cloud Practitioner", issuer: "Amazon Web Services", date: "Jul 2023" },
      ],
      languages: ["English (Fluent)", "Hindi (Native)", "Kannada (Intermediate)"],
      achievements: ["Winner, College Coding Hackathon 2022"],
      references: [],
    },
  },

  // IT Fresher (Right Sidebar)
  it_fresher_right: {
    name: "IT Fresher (Right Sidebar)",
    previewImage: "/templates/previews/it_fresher_right.png",
    category: "Job-Specific",
    premium: false,
    layout: {
      sectionsOrder: ["personal", "summary", "skills", "projects", "education", "certifications", "languages", "customSections"],
      sidebarSections: ["personal.photo", "skills", "languages"],
      mainSections: ["personal", "summary", "projects", "education", "certifications"],
      showIcons: true,
      columns: 2,
      sidebar: "right",
      sidebarWidth: "30%",
    },
    styles: {
      fontFamily: "'Poppins', sans-serif",
      fontSize: "11pt",
      lineHeight: "1.5",
      colors: {
        primary: "#1f2937",
        secondary: "#6b7280",
        accent: "#374151",
        text: "#111827",
        background: "#ffffff",
        sidebar: "#f9fafb",
      },
      photo: {
        shape: "circle",
        size: "110px",
        border: "2px solid #374151",
      },
    },
    defaultData: {
      personal: {
        name: "Ishita Jain",
        email: "ishita.jain@example.com",
        phone: "+91 87654 32109",
        address: "Noida, Uttar Pradesh, India",
        dateOfBirth: "28 Feb 2001",
        gender: "female",
        maritalStatus: "single",
        nationality: "US",
        linkedin: "linkedin.com/in/ishitajain",
        github: "github.com/ishitajain",
        photo: "",
      },
      summary: "Recent IT graduate with expertise in web development and a passion for building user-friendly applications.",
      skills: [
        "HTML5",
        "CSS3",
        "JavaScript",
        "React.js",
        "Vue.js",
        "Node.js",
        "MongoDB",
        "Git",
        "UI/UX Design",
        "Agile",
        "Testing",
      ],
      projects: [
        {
          title: "Portfolio Website",
          description: "Designed and deployed a personal portfolio using Vue.js and Firebase, showcasing 5+ projects.",
          startDate: "Mar 2023",
          endDate: "May 2023",
          technologies: "Vue.js, Firebase",
        },
        {
          title: "Chat Application",
          description: "Built a real-time chat app with React and Socket.io, supporting 100+ simultaneous users.",
          startDate: "Nov 2022",
          endDate: "Feb 2023",
          technologies: "React, Socket.io, Node.js",
        },
      ],
      experience: [],
      education: [
        {
          degree: "B.Tech in Information Technology",
          institution: "Jaypee Institute of Information Technology",
          startDate: "2019",
          endDate: "2023",
          grade: "CGPA: 8.7/10",
        },
        {
          degree: "Class XII (CBSE)",
          institution: "Amity International School, Noida",
          startDate: "2017",
          endDate: "2019",
          grade: "Percentage: 90%",
        },
      ],
      certifications: [
        { title: "Full Stack Development", issuer: "Udemy", date: "Jun 2023" },
        { title: "UI/UX Design Basics", issuer: "Coursera", date: "Aug 2023" },
      ],
      languages: ["English (Fluent)", "Hindi (Native)"],
      achievements: ["Top 10, National Coding Challenge 2022"],
      references: [],
    },
  },

  // Bank PO (Left Sidebar)
  bank_po_left: {
    name: "Bank PO (Left Sidebar)",
    previewImage: "/templates/previews/bank_po_left.png",
    category: "Job-Specific",
    premium: false,
    layout: {
      sectionsOrder: ["personal", "summary", "experience", "education", "skills", "certifications", "achievements", "languages", "customSections"],
      sidebarSections: ["personal.photo", "skills"],
      mainSections: ["personal", "summary", "experience", "education", "certifications", "achievements"],
      showIcons: false,
      columns: 2,
      sidebar: "left",
      sidebarWidth: "28%",
    },
    styles: {
      fontFamily: "'Times New Roman', serif",
      fontSize: "12pt",
      lineHeight: "1.6",
      colors: {
        primary: "#111827",
        secondary: "#6b7280",
        accent: "#374151",
        text: "#1f2937",
        background: "#ffffff",
        sidebar: "#f9fafb",
      },
      photo: {
        shape: "circle",
        size: "110px",
        border: "2px solid #111827",
      },
    },
    defaultData: {
      personal: {
        name: "Priya Gupta",
        email: "priya.gupta@example.com",
        phone: "+91 87654 32109",
        address: "Mumbai, Maharashtra, India",
        dateOfBirth: "22 Aug 1998",
        gender: "female",
        nationality: "US",
        maritalStatus: "Single",
        fatherName: "Ramesh Gupta",
        photo: "",
      },
      summary: "Detail-oriented commerce graduate with a strong foundation in banking operations and customer service, targeting a Probationary Officer role.",
      skills: [
        "Financial Analysis",
        "Customer Relationship Management",
        "MS Excel",
        "Accounting Principles",
        "Team Coordination",
        "Risk Assessment",
        "Communication",
      ],
      projects: [],
      experience: [
        {
          title: "Banking Intern",
          company: "HDFC Bank",
          startDate: "Jun 2022",
          endDate: "Dec 2022",
          description: "Processed 500+ transactions monthly, assisted in account management, and improved customer query resolution time by 15%.",
        },
        {
          title: "Finance Assistant",
          company: "Kotak Mahindra Bank",
          startDate: "Jan 2021",
          endDate: "May 2022",
          description: "Supported loan processing and maintained financial records for 200+ clients.",
        },
      ],
      education: [
        {
          degree: "B.Com (Banking & Finance)",
          institution: "University of Mumbai",
          startDate: "2019",
          endDate: "2022",
          grade: "Percentage: 78%",
        },
        {
          degree: "Class XII (Commerce)",
          institution: "St. Xavier's College, Mumbai",
          startDate: "2017",
          endDate: "2019",
          grade: "Percentage: 85%",
        },
      ],
      certifications: [
        { title: "Certified Banking Associate", issuer: "IIBF", date: "Jan 2023" },
        { title: "NISM Series V-A", issuer: "NISM", date: "Mar 2023" },
      ],
      languages: ["English (Fluent)", "Hindi (Fluent)", "Marathi (Native)"],
      achievements: ["Ranked Top 5% in Bank PO Mock Tests", "Best Intern Award, HDFC Bank, 2022"],
      references: [
        {
          name: "Mr. Sanjay Patel",
          position: "Branch Manager",
          company: "HDFC Bank",
          contact: "sanjay.patel@hdfcbank.com | +91 98765 43212",
        },
      ],
    },
  },

  // Bank PO (Right Sidebar)
  bank_po_right: {
    name: "Bank PO (Right Sidebar)",
    previewImage: "/templates/previews/bank_po_right.png",
    category: "Job-Specific",
    premium: false,
    layout: {
      sectionsOrder: ["personal", "summary", "experience", "education", "skills", "certifications", "achievements", "languages", "customSections"],
      sidebarSections: ["personal.photo", "skills"],
      mainSections: ["personal", "summary", "experience", "education", "certifications", "achievements"],
      showIcons: false,
      columns: 2,
      sidebar: "right",
      sidebarWidth: "28%",
    },
    styles: {
      fontFamily: "'Times New Roman', serif",
      fontSize: "12pt",
      lineHeight: "1.6",
      colors: {
        primary: "#111827",
        secondary: "#6b7280",
        accent: "#374151",
        text: "#1f2937",
        background: "#ffffff",
        sidebar: "#f9fafb",
      },
      photo: {
        shape: "circle",
        size: "110px",
        border: "2px solid #111827",
      },
    },
    defaultData: {
      personal: {
        name: "Amit Patel",
        email: "amit.patel@example.com",
        phone: "+91 76543 21098",
        address: "Ahmedabad, Gujarat, India",
        dateOfBirth: "15 Oct 1997",
        gender: "male",
        nationality: "US",
        maritalStatus: "Single",
        fatherName: "Vijay Patel",
        photo: "",
      },
      summary: "Organized and analytical B.Com graduate with experience in financial operations, aiming to excel as a Bank PO.",
      skills: [
        "Banking Operations",
        "Accounting",
        "Customer Service",
        "MS Office",
        "Data Analysis",
        "Compliance",
        "Teamwork",
      ],
      projects: [],
      experience: [
        {
          title: "Bank Teller",
          company: "ICICI Bank",
          startDate: "Jul 2021",
          endDate: "Present",
          description: "Handled 600+ daily transactions, achieving a 98% accuracy rate. Assisted in customer onboarding.",
        },
        {
          title: "Finance Intern",
          company: "Axis Bank",
          startDate: "Jan 2021",
          endDate: "Jun 2021",
          description: "Processed 150+ loan applications and conducted credit checks.",
        },
      ],
      education: [
        {
          degree: "B.Com (Accounting)",
          institution: "Gujarat University",
          startDate: "2018",
          endDate: "2021",
          grade: "Percentage: 80%",
        },
        {
          degree: "Class XII (Commerce)",
          institution: "HL Commerce College, Ahmedabad",
          startDate: "2016",
          endDate: "2018",
          grade: "Percentage: 83%",
        },
      ],
      certifications: [
        { title: "JAIIB", issuer: "IIBF", date: "Feb 2022" },
        { title: "Tally ERP 9", issuer: "Tally Education", date: "May 2021" },
      ],
      languages: ["English (Fluent)", "Gujarati (Native)", "Hindi (Fluent)"],
      achievements: ["Top Performer, ICICI Bank Teller Training, 2021"],
      references: [
        {
          name: "Ms. Neha Shah",
          position: "Branch Manager",
          company: "ICICI Bank",
          contact: "neha.shah@icicibank.com | +91 98765 43213",
        },
      ],
    },
  },

  // Government Job (Left Sidebar)
  government_job_left: {
    name: "Government Job (Left Sidebar)",
    previewImage: "/templates/previews/government_job_left.png",
    category: "Job-Specific",
    premium: false,
    layout: {
      sectionsOrder: ["personal", "summary", "experience", "education", "skills", "certifications", "languages", "references", "customSections"],
      sidebarSections: ["personal.photo", "skills", "languages"],
      mainSections: ["personal", "summary", "experience", "education", "certifications", "references"],
      showIcons: false,
      columns: 2,
      sidebar: "left",
      sidebarWidth: "30%",
    },
    styles: {
      fontFamily: "'Lato', sans-serif",
      fontSize: "12pt",
      lineHeight: "1.6",
      colors: {
        primary: "#1f2937",
        secondary: "#6b7280",
        accent: "#374151",
        text: "#111827",
        background: "#ffffff",
        sidebar: "#f1f5f9",
      },
      photo: {
        shape: "circle",
        size: "110px",
        border: "2px solid #1f2937",
      },
    },
    defaultData: {
      personal: {
        name: "Rahul Verma",
        email: "rahul.verma@example.com",
        phone: "+91 76543 21098",
        address: "New Delhi, India",
        dateOfBirth: "10 Nov 1995",
        nationality: "US",
        maritalStatus: "Married",
        fatherName: "Anil Verma",
        photo: "",
      },
      summary: "Dedicated professional with over 2 years of administrative experience, adept at managing records and public coordination, targeting government roles like UPSC or SSC.",
      skills: [
        "Public Administration",
        "Record Keeping",
        "MS Office Suite",
        "Policy Compliance",
        "Communication",
        "Data Entry",
        "Team Management",
      ],
      projects: [],
      experience: [
        {
          title: "Administrative Assistant",
          company: "Delhi Municipal Corporation",
          startDate: "Mar 2021",
          endDate: "Feb 2023",
          description: "Managed records for 1000+ citizens and coordinated public inquiries, reducing response time by 25%.",
        },
        {
          title: "Clerk",
          company: "Ministry of Home Affairs",
          startDate: "Jun 2019",
          endDate: "Feb 2021",
          description: "Processed 300+ applications monthly and maintained confidential files.",
        },
      ],
      education: [
        {
          degree: "B.A. in Public Administration",
          institution: "University of Delhi",
          startDate: "2016",
          endDate: "2019",
          grade: "Percentage: 72%",
        },
        {
          degree: "Class XII (Arts)",
          institution: "Kendriya Vidyalaya, Delhi",
          startDate: "2014",
          endDate: "2016",
          grade: "Percentage: 88%",
        },
      ],
      certifications: [
        { title: "Certificate in Public Policy", issuer: "IGNOU", date: "Dec 2022" },
        { title: "Computer Applications", issuer: "NIIT", date: "May 2020" },
      ],
      languages: ["English (Fluent)", "Hindi (Native)"],
      achievements: ["Employee of the Month, Delhi Municipal Corporation, Jan 2022"],
      references: [
        {
          name: "Mr. Anil Kumar",
          position: "Supervisor",
          company: "Delhi Municipal Corporation",
          contact: "anil.kumar@example.com | +91 98765 43211",
        },
      ],
    },
  },

  // Government Job (Right Sidebar)
  government_job_right: {
    name: "Government Job (Right Sidebar)",
    previewImage: "/templates/previews/government_job_right.png",
    category: "Job-Specific",
    premium: false,
    layout: {
      sectionsOrder: ["personal", "summary", "experience", "education", "skills", "certifications", "languages", "references", "customSections"],
      sidebarSections: ["personal.photo", "skills", "languages"],
      mainSections: ["personal", "summary", "experience", "education", "certifications", "references"],
      showIcons: false,
      columns: 2,
      sidebar: "right",
      sidebarWidth: "30%",
    },
    styles: {
      fontFamily: "'Lato', sans-serif",
      fontSize: "12pt",
      lineHeight: "1.6",
      colors: {
        primary: "#1f2937",
        secondary: "#6b7280",
        accent: "#374151",
        text: "#111827",
        background: "#ffffff",
        sidebar: "#f1f5f9",
      },
      photo: {
        shape: "circle",
        size: "110px",
        border: "2px solid #10b981",
      },
    },
    defaultData: {
      personal: {
        name: "Pooja Yadav",
        email: "pooja.yadav@example.com",
        phone: "+91 65432 10987",
        address: "Lucknow, Uttar Pradesh, India",
        dateOfBirth: "17 Jun 1994",
        nationality: "US",
        maritalStatus: "Single",
        fatherName: "Rajesh Yadav",
        photo: "",
      },
      summary: "Committed public servant with 3 years of experience in clerical and administrative roles, aiming for government positions.",
      skills: [
        "Office Administration",
        "Data Management",
        "MS Word",
        "Excel",
        "Public Dealing",
        "Report Writing",
        "Organizational Skills",
      ],
      projects: [],
      experience: [
        {
          title: "Senior Clerk",
          company: "UP State Electricity Board",
          startDate: "Apr 2020",
          endDate: "Present",
          description: "Managed billing records for 2000+ customers and prepared monthly reports for management.",
        },
        {
          title: "Office Assistant",
          company: "District Collector's Office",
          startDate: "Jul 2019",
          endDate: "Mar 2020",
          description: "Assisted in file management and public grievance redressal for 500+ cases.",
        },
      ],
      education: [
        {
          degree: "B.A. in Political Science",
          institution: "Lucknow University",
          startDate: "2016",
          endDate: "2019",
          grade: "Percentage: 70%",
        },
        {
          degree: "Class XII (Arts)",
          institution: "St. Mary's Convent, Lucknow",
          startDate: "2014",
          endDate: "2016",
          grade: "Percentage: 82%",
        },
      ],
      certifications: [
        { title: "Certificate in Office Management", issuer: "IGNOU", date: "Jan 2021" },
        { title: "Basic Computer Skills", issuer: "CSC Academy", date: "Aug 2020" },
      ],
      languages: ["English (Fluent)", "Hindi (Native)"],
      achievements: ["Best Employee Award, UPSEB, Dec 2021"],
      references: [
        {
          name: "Mr. Vivek Singh",
          position: "Office Supervisor",
          company: "UP State Electricity Board",
          contact: "vivek.singh@example.com | +91 98765 43214",
        },
      ],
    },
  },

  // Teacher (Left Sidebar)
  teacher_left: {
    name: "Teacher (Left Sidebar)",
    previewImage: "/templates/previews/teacher_left.png",
    category: "Job-Specific",
    premium: false,
    layout: {
      sectionsOrder: ["personal", "summary", "experience", "education", "skills", "certifications", "achievements", "languages", "customSections"],
      sidebarSections: ["personal.photo", "skills"],
      mainSections: ["personal", "summary", "experience", "education", "certifications", "achievements"],
      showIcons: true,
      columns: 2,
      sidebar: "left",
      sidebarWidth: "30%",
    },
    styles: {
      fontFamily: "'Georgia', serif",
      fontSize: "11pt",
      lineHeight: "1.6",
      colors: {
        primary: "#1f2937",
        secondary: "#ca8a04",
        accent: "#f59e0b",
        text: "#1f2937",
        background: "#ffffff",
        sidebar: "#f9fafb",
      },
      photo: {
        shape: "circle",
        size: "110px",
        border: "2px solid #f59e0b",
      },
    },
    defaultData: {
      personal: {
        name: "Sneha Patel",
        email: "sneha.patel@example.com",
        phone: "+91 65432 10987",
        address: "Ahmedabad, Gujarat, India",
        dateOfBirth: "05 Mar 1992",
        gender: "female",
        maritalStatus: "single",
        nationality: "US",
        photo: "",
      },
      summary: "Passionate educator with 3+ years of experience in primary education, committed to fostering student growth and academic excellence.",
      skills: [
        "Classroom Management",
        "Curriculum Development",
        "Communication",
        "MS Office",
        "Student Counseling",
        "Lesson Planning",
        "Assessment Design",
      ],
      projects: [],
      experience: [
        {
          title: "Primary Teacher",
          company: "St. Xavier's School",
          startDate: "Jul 2020",
          endDate: "Jun 2023",
          description: "Taught English and Math to Class 5 students, improving average scores by 15%. Organized 10+ extracurricular activities.",
        },
        {
          title: "Teaching Assistant",
          company: "DPS Ahmedabad",
          startDate: "Aug 2019",
          endDate: "Jun 2020",
          description: "Supported lesson delivery and managed classroom activities for 30+ students.",
        },
      ],
      education: [
        {
          degree: "B.Ed",
          institution: "Gujarat University",
          startDate: "2018",
          endDate: "2020",
          grade: "Percentage: 85%",
        },
        {
          degree: "B.A. in English",
          institution: "Gujarat University",
          startDate: "2015",
          endDate: "2018",
          grade: "Percentage: 78%",
        },
      ],
      certifications: [
        { title: "CTET Certified", issuer: "CBSE", date: "Dec 2020" },
        { title: "Diploma in Early Childhood Education", issuer: "IGNOU", date: "Jun 2021" },
      ],
      languages: ["English (Fluent)", "Gujarati (Native)", "Hindi (Fluent)"],
      achievements: ["Best Teacher Award, St. Xavier's School, 2022"],
      references: [
        {
          name: "Mrs. Anita Desai",
          position: "Principal",
          company: "St. Xavier's School",
          contact: "anita.desai@example.com | +91 98765 43215",
        },
      ],
    },
  },

  // Teacher (Right Sidebar)
  teacher_right: {
    name: "Teacher (Right Sidebar)",
    previewImage: "/templates/previews/teacher_right.png",
    category: "Job-Specific",
    premium: false,
    layout: {
      sectionsOrder: ["personal", "summary", "experience", "education", "skills", "certifications", "achievements", "languages", "customSections"],
      sidebarSections: ["personal.photo", "skills"],
      mainSections: ["personal", "summary", "experience", "education", "certifications", "achievements"],
      showIcons: true,
      columns: 2,
      sidebar: "right",
      sidebarWidth: "30%",
    },
    styles: {
      fontFamily: "'Georgia', serif",
      fontSize: "11pt",
      lineHeight: "1.6",
      colors: {
        primary: "#1f2937",
        secondary: "#ca8a04",
        accent: "#f59e0b",
        text: "#1f2937",
        background: "#ffffff",
        sidebar: "#f9fafb",
      },
      photo: {
        shape: "circle",
        size: "110px",
        border: "2px solid #f59e0b",
      },
    },
    defaultData: {
      personal: {
        name: "Rakesh Kumar",
        email: "rakesh.kumar@example.com",
        phone: "+91 54321 09876",
        address: "Patna, Bihar, India",
        dateOfBirth: "20 Apr 1990",
        gender: "male",
        maritalStatus: "married",
        nationality: "US",
        photo: "",
      },
      summary: "Experienced secondary school teacher with 5 years of teaching science, focused on interactive learning and student development.",
      skills: [
        "Science Education",
        "Lesson Planning",
        "Student Assessment",
        "Classroom Discipline",
        "Communication",
        "Lab Management",
        "Mentoring",
      ],
      projects: [],
      experience: [
        {
          title: "Science Teacher",
          company: "DAV Public School, Patna",
          startDate: "Jun 2018",
          endDate: "Present",
          description: "Taught Physics and Chemistry to Classes 9-10, boosting pass rates by 20%. Conducted 15+ science workshops.",
        },
        {
          title: "Assistant Teacher",
          company: "Kendriya Vidyalaya, Patna",
          startDate: "Aug 2016",
          endDate: "May 2018",
          description: "Assisted in science labs and prepared teaching aids for 200+ students.",
        },
      ],
      education: [
        {
          degree: "B.Ed",
          institution: "Patna University",
          startDate: "2015",
          endDate: "2017",
          grade: "Percentage: 82%",
        },
        {
          degree: "B.Sc in Physics",
          institution: "Magadh University",
          startDate: "2012",
          endDate: "2015",
          grade: "Percentage: 75%",
        },
      ],
      certifications: [
        { title: "CTET Certified", issuer: "CBSE", date: "Jul 2017" },
        { title: "Science Teaching Certificate", issuer: "NCERT", date: "Sep 2018" },
      ],
      languages: ["English (Fluent)", "Hindi (Native)", "Bhojpuri (Intermediate)"],
      achievements: ["Outstanding Teacher Award, DAV Public School, 2021"],
      references: [
        {
          name: "Mr. Vinod Sharma",
          position: "Principal",
          company: "DAV Public School",
          contact: "vinod.sharma@example.com | +91 98765 43216",
        },
      ],
    },
  },

  // Healthcare (Left Sidebar)
  healthcare_left: {
    name: "Healthcare Professional (Left Sidebar)",
    previewImage: "/templates/previews/healthcare_left.png",
    category: "Job-Specific",
    premium: false,
    layout: {
      sectionsOrder: ["personal", "summary", "experience", "education", "skills", "certifications", "languages"],
      sidebarSections: ["personal.photo", "skills", "languages"],
      mainSections: ["personal", "summary", "experience", "education", "certifications"],
      showIcons: true,
      columns: 2,
      sidebar: "left",
      sidebarWidth: "30%",
    },
    styles: {
      fontFamily: "'Roboto', sans-serif",
      fontSize: "11pt",
      lineHeight: "1.5",
      colors: {
        primary: "#111827",
        secondary: "#22d3ee",
        accent: "#06b6d4",
        text: "#164e63",
        background: "#ffffff",
        sidebar: "linear-gradient(135deg, #e0f2fe 0%, #bae6fd 100%)",
      },
      photo: {
        shape: "circle",
        size: "110px",
        border: "2px solid #06b6d4",
      },
    },
    defaultData: {
      personal: {
        name: "Dr. Anjali Nair",
        email: "anjali.nair@example.com",
        phone: "+91 54321 09876",
        address: "Kochi, Kerala, India",
        dateOfBirth: "12 Jan 1990",
        gender: "female",
        maritalStatus: "single",
        nationality: "US",
        photo: "",
      },
      summary: "Compassionate MBBS doctor with 4 years of clinical experience in general medicine, dedicated to patient care and community health.",
      skills: [
        "Patient Diagnosis",
        "Emergency Care",
        "Surgical Assistance",
        "Medical Records Management",
        "Team Leadership",
        "Health Education",
        "Clinical Research",
      ],
      projects: [],
      experience: [
        {
          title: "Resident Doctor",
          company: "Aster Medcity",
          startDate: "Aug 2019",
          endDate: "Jul 2023",
          description: "Managed OPD for 50+ patients daily and handled emergency cases, reducing wait times by 20%. Trained 5 junior staff.",
        },
        {
          title: "Medical Intern",
          company: "Government Medical College, Kochi",
          startDate: "Jul 2018",
          endDate: "Jul 2019",
          description: "Assisted in 100+ surgeries and maintained patient records.",
        },
      ],
      education: [
        {
          degree: "MBBS",
          institution: "Kerala University of Health Sciences",
          startDate: "2013",
          endDate: "2019",
          grade: "Percentage: 82%",
        },
        {
          degree: "Class XII (Science)",
          institution: "St. Teresa's School, Kochi",
          startDate: "2011",
          endDate: "2013",
          grade: "Percentage: 90%",
        },
      ],
      certifications: [
        { title: "BLS Certification", issuer: "American Heart Association", date: "Jun 2020" },
        { title: "ACLS Certification", issuer: "AHA", date: "Aug 2021" },
      ],
      languages: ["English (Fluent)", "Malayalam (Native)", "Hindi (Intermediate)"],
      achievements: ["Best Resident Doctor, Aster Medcity, 2022"],
      references: [
        {
          name: "Dr. Rajesh Menon",
          position: "Senior Consultant",
          company: "Aster Medcity",
          contact: "rajesh.menon@example.com | +91 98765 43217",
        },
      ],
    },
  },

  // Healthcare (Right Sidebar)
  healthcare_right: {
    name: "Healthcare Professional (Right Sidebar)",
    previewImage: "/templates/previews/healthcare_right.png",
    category: "Job-Specific",
    premium: false,
    layout: {
      sectionsOrder: ["personal", "summary", "experience", "education", "skills", "certifications", "languages"],
      sidebarSections: ["personal.photo", "skills", "languages"],
      mainSections: ["personal", "summary", "experience", "education", "certifications"],
      showIcons: true,
      columns: 2,
      sidebar: "right",
      sidebarWidth: "30%",
    },
    styles: {
      fontFamily: "'Roboto', sans-serif",
      fontSize: "11pt",
      lineHeight: "1.5",
      colors: {
        primary: "#111827",
        secondary: "#22d3ee",
        accent: "#06b6d4",
        text: "#164e63",
        background: "#ffffff",
        sidebar: "linear-gradient(135deg, #e0f2fe 0%, #bae6fd 100%)",
      },
      photo: {
        shape: "circle",
        size: "110px",
        border: "2px solid #06b6d4",
      },
    },
    defaultData: {
      personal: {
        name: "Dr. Sanjay Reddy",
        email: "sanjay.reddy@example.com",
        phone: "+91 43210 98765",
        address: "Hyderabad, Telangana, India",
        dateOfBirth: "08 Aug 1989",
        gender: "male",
        maritalStatus: "married",
        nationality: "US",
        photo: "",
      },
      summary: "Skilled physician with 5 years of experience in internal medicine, committed to improving patient outcomes through evidence-based practice.",
      skills: [
        "Internal Medicine",
        "Patient Care",
        "Diagnostics",
        "Emergency Medicine",
        "Team Coordination",
        "Medical Research",
        "Health Informatics",
      ],
      projects: [],
      experience: [
        {
          title: "Senior Resident",
          company: "Apollo Hospitals",
          startDate: "Sep 2018",
          endDate: "Present",
          description: "Managed 60+ patient cases monthly, introduced telemedicine protocols, improving access by 30%.",
        },
        {
          title: "Junior Doctor",
          company: "Osmania General Hospital",
          startDate: "Jul 2017",
          endDate: "Aug 2018",
          description: "Assisted in ward management and conducted 50+ patient assessments weekly.",
        },
      ],
      education: [
        {
          degree: "MBBS",
          institution: "Osmania Medical College",
          startDate: "2012",
          endDate: "2017",
          grade: "Percentage: 80%",
        },
        {
          degree: "Class XII (Science)",
          institution: "Narayana Junior College, Hyderabad",
          startDate: "2010",
          endDate: "2012",
          grade: "Percentage: 93%",
        },
      ],
      certifications: [
        { title: "BLS Certification", issuer: "American Heart Association", date: "Oct 2018" },
        { title: "Certified in Telemedicine", issuer: "IIMA", date: "Mar 2020" },
      ],
      languages: ["English (Fluent)", "Telugu (Native)", "Hindi (Fluent)"],
      achievements: ["Excellence in Patient Care Award, Apollo Hospitals, 2021"],
      references: [
        {
          name: "Dr. Priya Rao",
          position: "Chief Consultant",
          company: "Apollo Hospitals",
          contact: "priya.rao@example.com | +91 98765 43218",
        },
      ],
    },
  },

  // Engineering Fresher (Left Sidebar)
  engineering_fresher_left: {
    name: "Engineering Fresher (Left Sidebar)",
    previewImage: "/templates/previews/engineering_fresher_left.png",
    category: "Job-Specific",
    premium: false,
    layout: {
      sectionsOrder: ["personal", "summary", "skills", "projects", "education", "certifications", "achievements", "languages", "customSections"],
      sidebarSections: ["personal.photo", "skills"],
      mainSections: ["personal", "summary", "projects", "education", "certifications", "achievements"],
      showIcons: true,
      columns: 2,
      sidebar: "left",
      sidebarWidth: "30%",
    },
    styles: {
      fontFamily: "'Poppins', sans-serif",
      fontSize: "11pt",
      lineHeight: "1.5",
      colors: {
        primary: "#1f2937",
        secondary: "#34d399",
        accent: "#10b981",
        text: "#1f2937",
        background: "#ffffff",
        sidebar: "linear-gradient(135deg, #d1fae5 0%, #a7f3d0 100%)",
      },
      photo: {
        shape: "circle",
        size: "110px",
        border: "2px solid #10b981",
      },
    },
    defaultData: {
      personal: {
        name: "Vikram Singh",
        email: "vikram.singh@example.com",
        phone: "+91 43210 98765",
        location: "Chennai, Tamil Nadu, India",
        dateOfBirth: "25 Dec 1999",
        gender: "male",
        maritalStatus: "single",
        nationality: "US",
        linkedin: "linkedin.com/in/vikramsingh",
        github: "github.com/vikramsingh",
        photo: "",
      },
      summary: "Enthusiastic B.E. Mechanical Engineering graduate with hands-on project experience and a strong foundation in design and analysis.",
      skills: [
        "AutoCAD",
        "SolidWorks",
        "MATLAB",
        "Mechanical Design",
        "Finite Element Analysis",
        "Problem Solving",
        "Teamwork",
        "Technical Writing",
      ],
      projects: [
        {
          title: "Solar-Powered Water Pump",
          description: "Designed and prototyped a solar-powered pump, improving efficiency by 30% using SolidWorks and MATLAB simulations.",
          startDate: "Feb 2022",
          endDate: "May 2022",
          technologies: "SolidWorks, MATLAB",
        },
        {
          title: "Gearbox Optimization",
          description: "Redesigned a gearbox for a mini-project, reducing weight by 15% while maintaining strength.",
          startDate: "Aug 2021",
          endDate: "Dec 2021",
          technologies: "AutoCAD",
        },
      ],
      experience: [],
      education: [
        {
          degree: "B.E. in Mechanical Engineering",
          institution: "Anna University",
          startDate: "2018",
          endDate: "2022",
          grade: "CGPA: 8.8/10",
        },
        {
          degree: "Class XII (Science)",
          institution: "Chinmaya Vidyalaya, Chennai",
          startDate: "2016",
          endDate: "2018",
          grade: "Percentage: 89%",
        },
      ],
      certifications: [
        { title: "AutoCAD Certified Professional", issuer: "Autodesk", date: "Jul 2022" },
        { title: "MATLAB Fundamentals", issuer: "MathWorks", date: "Sep 2022" },
      ],
      languages: ["English (Fluent)", "Tamil (Native)", "Hindi (Intermediate)"],
      achievements: ["1st Prize, National Engineering Design Contest, 2022"],
      references: [],
    },
  },

  // Engineering Fresher (Right Sidebar)
  engineering_fresher_right: {
    name: "Engineering Fresher (Right Sidebar)",
    previewImage: "/templates/previews/engineering_fresher_right.png",
    category: "Job-Specific",
    premium: false,
    layout: {
      sectionsOrder: ["personal", "summary", "skills", "projects", "education", "certifications", "achievements", "languages", "customSections"],
      sidebarSections: ["personal.photo", "skills"],
      mainSections: ["personal", "summary", "projects", "education", "certifications", "achievements"],
      showIcons: true,
      columns: 2,
      sidebar: "right",
      sidebarWidth: "30%",
    },
    styles: {
      fontFamily: "'Poppins', sans-serif",
      fontSize: "11pt",
      lineHeight: "1.5",
      colors: {
        primary: "#1f2937",
        secondary: "#34d399",
        accent: "#10b981",
        text: "#1f2937",
        background: "#ffffff",
        sidebar: "linear-gradient(135deg, #d1fae5 0%, #a7f3d0 100%)",
      },
      photo: {
        shape: "circle",
        size: "110px",
        border: "2px solid #10b981",
      },
    },
    defaultData: {
      personal: {
        name: "Deepika Rao",
        email: "deepika.rao@example.com",
        phone: "+91 32109 87654",
        location: "Bengaluru, Karnataka, India",
        dateOfBirth: "14 Jan 2000",
        gender: "female",
        maritalStatus: "single",
        nationality: "US",
        linkedin: "linkedin.com/in/deepikarao",
        github: "github.com/deepikarao",
        photo: "",
      },
      summary: "Motivated B.Tech Civil Engineering graduate with a strong interest in structural design and sustainable infrastructure.",
      skills: [
        "AutoCAD",
        "STAAD.Pro",
        "Civil 3D",
        "Structural Analysis",
        "Project Planning",
        "Surveying",
        "Team Collaboration",
        "Technical Drawing",
      ],
      projects: [
        {
          title: "Sustainable Bridge Design",
          description: "Designed a pedestrian bridge using AutoCAD and STAAD.Pro, optimizing material use by 20%.",
          startDate: "Mar 2022",
          endDate: "Jun 2022",
          technologies: "AutoCAD, STAAD.Pro",
        },
        {
          title: "Rainwater Harvesting System",
          description: "Developed a campus rainwater harvesting model, reducing water waste by 30%.",
          startDate: "Sep 2021",
          endDate: "Dec 2021",
          technologies: "Civil 3D",
        },
      ],
      experience: [],
      education: [
        {
          degree: "B.Tech in Civil Engineering",
          institution: "RV College of Engineering",
          startDate: "2018",
          endDate: "2022",
          grade: "CGPA: 8.6/10",
        },
        {
          degree: "Class XII (Science)",
          institution: "National Public School, Bengaluru",
          startDate: "2016",
          endDate: "2018",
          grade: "Percentage: 91%",
        },
      ],
      certifications: [
        { title: "AutoCAD for Civil Engineers", issuer: "Autodesk", date: "Aug 2022" },
        { title: "Structural Design Basics", issuer: "NPTEL", date: "Oct 2022" },
      ],
      languages: ["English (Fluent)", "Kannada (Native)", "Hindi (Fluent)"],
      achievements: ["2nd Place, Civil Engineering Symposium Project, 2022"],
      references: [],
    },
  },

  // Creative Media (Left Sidebar)
  creative_media_left: {
    name: "Creative Media (Left Sidebar)",
    previewImage: "/templates/previews/creative_media_left.png",
    category: "Job-Specific",
    premium: false,
    layout: {
      sectionsOrder: ["personal", "summary", "experience", "education", "skills", "portfolio", "achievements", "languages", "customSections"],
      sidebarSections: ["personal.photo", "skills"],
      mainSections: ["personal", "summary", "experience", "education", "portfolio", "achievements"],
      showIcons: true,
      columns: 2,
      sidebar: "left",
      sidebarWidth: "30%",
    },
    styles: {
      fontFamily: "'Poppins', sans-serif",
      fontSize: "11pt",
      lineHeight: "1.5",
      colors: {
        primary: "#111827",
        secondary: "#db2777",
        accent: "#ec4899",
        text: "#1f2937",
        background: "#ffffff",
        sidebar: "linear-gradient(135deg, #fce7f3 0%, #f9a8d4 100%)",
      },
      photo: {
        shape: "circle",
        size: "120px",
        border: "3px solid #ec4899",
      },
    },
    defaultData: {
      personal: {
        name: "Neha Kapoor",
        email: "neha.kapoor@example.com",
        phone: "+91 32109 87654",
        address: "Mumbai, Maharashtra, India",
        dateOfBirth: "",
        gender: "",
        maritalStatus: "",
        portfolio: "behance.net/nehakapoor",
        linkedin: "linkedin.com/in/nehakapoor",
        photo: "",
      },
      summary: "Creative graphic designer with 2+ years of experience in branding and digital media, delivering visually stunning solutions.",
      skills: [
        "Adobe Photoshop",
        "Illustrator",
        "InDesign",
        "UI/UX Design",
        "Branding",
        "Typography",
        "Motion Graphics",
        "Social Media Design",
      ],
      projects: [],
      experience: [
        {
          title: "Graphic Designer",
          company: "Ogilvy India",
          startDate: "Jan 2022",
          endDate: "Dec 2023",
          description: "Designed campaigns for 10+ clients, boosting engagement by 25%. Created social media assets for national brands.",
        },
        {
          title: "Junior Designer",
          company: "Dentsu India",
          startDate: "Jun 2021",
          endDate: "Dec 2021",
          description: "Supported branding projects and produced 50+ marketing collaterals.",
        },
      ],
      education: [
        {
          degree: "B.Des in Graphic Design",
          institution: "NID Ahmedabad",
          startDate: "2018",
          endDate: "2021",
          grade: "Percentage: 80%",
        },
        {
          degree: "Class XII (Arts)",
          institution: "St. Mary's School, Mumbai",
          startDate: "2016",
          endDate: "2018",
          grade: "Percentage: 87%",
        },
      ],
      certifications: [
        { title: "Adobe Certified Expert - Photoshop", issuer: "Adobe", date: "Mar 2022" },
        { title: "UI/UX Design Specialization", issuer: "Coursera", date: "Sep 2021" },
      ],
      languages: ["English (Fluent)", "Hindi (Native)", "Marathi (Intermediate)"],
      achievements: ["Best Design Award, Ogilvy India, 2023"],
      portfolio: [
        { title: "Brand Identity for Startup", link: "behance.net/nehakapoor/startup", description: "Created logo and marketing materials." },
        { title: "Ad Campaign for FMCG", link: "behance.net/nehakapoor/fmcg", description: "Designed print and digital ads." },
      ],
      references: [
        {
          name: "Mr. Rohan Mehta",
          position: "Creative Director",
          company: "Ogilvy India",
          contact: "rohan.mehta@example.com | +91 98765 43219",
        },
      ],
    },
  },

  // Creative Media (Right Sidebar)
  creative_media_right: {
    name: "Creative Media (Right Sidebar)",
    previewImage: "/templates/previews/creative_media_right.png",
    category: "Job-Specific",
    premium: false,
    layout: {
      sectionsOrder: ["personal", "summary", "experience", "education", "skills", "portfolio", "achievements", "languages", "customSections"],
      sidebarSections: ["personal.photo", "skills"],
      mainSections: ["personal", "summary", "experience", "education", "portfolio", "achievements"],
      showIcons: true,
      columns: 2,
      sidebar: "right",
      sidebarWidth: "30%",
    },
    styles: {
      fontFamily: "'Poppins', sans-serif",
      fontSize: "11pt",
      lineHeight: "1.5",
      colors: {
        primary: "#111827",
        secondary: "#db2777",
        accent: "#ec4899",
        text: "#1f2937",
        background: "#ffffff",
        sidebar: "linear-gradient(135deg, #fce7f3 0%, #f9a8d4 100%)",
      },
      photo: {
        shape: "circle",
        size: "120px",
        border: "3px solid #ec4899",
      },
    },
    defaultData: {
      personal: {
        name: "Aakash Mehra",
        email: "aakash.mehra@example.com",
        phone: "+91 21098 76543",
        location: "Delhi, India",
        dateOfBirth: "",
        gender: "",
        maritalStatus: "",
        portfolio: "dribbble.com/aakashmehra",
        linkedin: "linkedin.com/in/aakashmehra",
        photo: "",
      },
      summary: "Innovative multimedia artist with 3 years of experience in video editing and animation, passionate about storytelling through visuals.",
      skills: [
        "Adobe Premiere Pro",
        "After Effects",
        "Photoshop",
        "Video Editing",
        "Animation",
        "Storyboarding",
        "Sound Design",
        "Creative Direction",
      ],
      projects: [],
      experience: [
        {
          title: "Video Editor",
          company: "Zee Media",
          startDate: "Feb 2021",
          endDate: "Present",
          description: "Edited 50+ promotional videos, increasing viewership by 40%. Collaborated with 5+ directors on creative projects.",
        },
        {
          title: "Assistant Editor",
          company: "Times Network",
          startDate: "Aug 2020",
          endDate: "Jan 2021",
          description: "Supported editing for news segments and produced 20+ short-form content pieces.",
        },
      ],
      education: [
        {
          degree: "BFA in Animation",
          institution: "JMI Delhi",
          startDate: "2017",
          endDate: "2020",
          grade: "Percentage: 83%",
        },
        {
          degree: "Class XII (Arts)",
          institution: "Modern School, Delhi",
          startDate: "2015",
          endDate: "2017",
          grade: "Percentage: 88%",
        },
      ],
      certifications: [
        { title: "Adobe Certified Professional - Premiere Pro", issuer: "Adobe", date: "May 2021" },
        { title: "Motion Graphics Fundamentals", issuer: "Udemy", date: "Oct 2020" },
      ],
      languages: ["English (Fluent)", "Hindi (Native)"],
      achievements: ["Featured Editor, Zee Media Creative Awards, 2022"],
      portfolio: [
        { title: "Short Film Animation", link: "dribbble.com/aakashmehra/film", description: "Animated a 2-minute short film." },
        { title: "TV Ad Edit", link: "dribbble.com/aakashmehra/ad", description: "Edited a 30-second commercial." },
      ],
      references: [
        {
          name: "Ms. Shalini Gupta",
          position: "Senior Producer",
          company: "Zee Media",
          contact: "shalini.gupta@example.com | +91 98765 43220",
        },
      ],
    },
  },

  // Healthcare Professional - Clean Medical Layout
  healthcare_professional: {
    name: "Healthcare Professional",
    previewImage: "/templates/previews/healthcare_professional.png",
    category: "Job-Specific",
    layout: {
      type: "medical",
      headerType: "medical-banner",
      sectionsOrder: ["personal", "summary", "experience", "education", "skills", "certifications", "licenses", "languages", "customSections"],
      sidebarSections: ["personal.photo", "skills", "certifications", "licenses"],
      mainSections: ["summary", "experience", "education"],
      showIcons: true,
      sidebar: "right",
      sidebarWidth: "32%",
      sectionCard: true,
      sectionDividers: false,
    },
    styles: {
      fontFamily: "'Lato', 'Helvetica Neue', sans-serif",
      fontSize: "10pt",
      lineHeight: "1.5",
      borderRadius: "12px",
      photo: {
        shape: "circle",
        size: "95px",
        border: "3px solid #1f2937",
        shadow: "0 4px 15px rgba(5, 150, 105, 0.25)",
      },
      colors: {
        primary: "#1f2937",
        secondary: "#10b981",
        accent: "#34d399",
        text: "#064e3b",
        background: "#ffffff",
        sidebar: "linear-gradient(135deg, #d1fae5 0%, #a7f3d0 100%)",
        headerGradient: "linear-gradient(135deg, #1f2937 0%, #10b981 100%)",
        cardBg: "#f0fdf4",
        border: "#bbf7d0",
      },
      icons: {
        experience: "🏥",
        education: "🎓",
        skills: "⚕️",
        certifications: "📋",
        licenses: "🏥"
      }
    },
    defaultData: {
      personal: {
        name: "Dr. Sarah Williams",
        email: "sarah.williams@hospital.com",
        phone: "+1 (555) 987-6543",
        location: "Boston, MA",
        dateOfBirth: "",
        gender: "",
        maritalStatus: "",
        linkedin: "linkedin.com/in/sarahwilliams",
        photo: "",
      },
      summary: "Dedicated healthcare professional with 8+ years of experience in patient care, clinical excellence, and healthcare innovation. Committed to improving patient outcomes through evidence-based practice.",
      skills: [
        "Patient Care",
        "Clinical Assessment", 
        "Electronic Health Records",
        "Medical Research",
        "Team Leadership",
        "Quality Improvement",
        "Patient Education",
        "Healthcare Technology"
      ],
      experience: [
        {
          title: "Senior Physician",
          company: "Massachusetts General Hospital",
          startDate: "Jan 2020",
          endDate: "Present",
          description: "Lead clinical team of 12 healthcare professionals, manage 200+ patient cases monthly, implement quality improvement initiatives resulting in 25% reduction in readmission rates."
        },
        {
          title: "Resident Physician",
          company: "Boston Medical Center",
          startDate: "Jul 2018",
          endDate: "Dec 2019",
          description: "Provided comprehensive patient care, conducted clinical research, mentored medical students and junior residents."
        }
      ],
      education: [
        {
          degree: "Doctor of Medicine (MD)",
          institution: "Harvard Medical School",
          startDate: "2014",
          endDate: "2018",
          grade: "GPA: 3.9/4.0"
        },
        {
          degree: "Bachelor of Science in Biology",
          institution: "MIT",
          startDate: "2010", 
          endDate: "2014",
          grade: "Magna Cum Laude"
        }
      ],
      certifications: [
        { title: "Board Certified Internal Medicine", issuer: "ABIM", date: "2019" },
        { title: "Advanced Cardiac Life Support (ACLS)", issuer: "AHA", date: "2023" },
        { title: "Basic Life Support (BLS)", issuer: "AHA", date: "2023" }
      ],
      licenses: [
        { title: "Medical License - Massachusetts", issuer: "MA Board of Registration", date: "2018" },
        { title: "DEA Registration", issuer: "DEA", date: "2019" }
      ],
      languages: ["English (Native)", "Spanish (Professional)", "French (Conversational)"]
    }
  },

  // Creative Designer - Portfolio Layout
  creative_designer: {
    name: "Creative Designer",
    previewImage: "/templates/previews/creative_designer.png",
    category: "Job-Specific",
    layout: {
      type: "creative",
      headerType: "creative-hero",
      sectionsOrder: ["personal", "summary", "portfolio", "experience", "skills", "education", "awards", "languages", "customSections"],
      sidebarSections: ["personal.photo", "skills", "education"],
      mainSections: ["summary", "portfolio", "experience", "awards"],
      showIcons: true,
      sidebar: "left",
      sidebarWidth: "30%",
      sectionCard: true,
      sectionDividers: false,
    },
    styles: {
      fontFamily: "'Poppins', 'Helvetica Neue', sans-serif",
      fontSize: "10pt",
      lineHeight: "1.5",
      borderRadius: "15px",
      photo: {
        shape: "rounded",
        size: "110px",
        border: "4px solid #ec4899",
        shadow: "0 6px 20px rgba(236, 72, 153, 0.3)",
      },
      colors: {
        primary: "#111827",
        secondary: "#ec4899",
        accent: "#f9a8d4",
        text: "#1f2937",
        background: "#ffffff",
        sidebar: "linear-gradient(135deg, #fce7f3 0%, #f9a8d4 100%)",
        headerGradient: "linear-gradient(135deg, #111827 0%, #ec4899 100%)",
        cardBg: "#fdf2f8",
        border: "#f9a8d4",
      },
      icons: {
        portfolio: "🎨",
        experience: "💼",
        skills: "✨",
        education: "🎓",
        awards: "🏆"
      }
    },
    defaultData: {
      personal: {
        name: "Emma Rodriguez",
        email: "emma@creativedesigns.com",
        phone: "+1 (555) 234-5678",
        location: "San Francisco, CA",
        dateOfBirth: "",
        gender: "",
        maritalStatus: "",
        portfolio: "emmarodriguez.design",
        linkedin: "linkedin.com/in/emmarodriguez",
        behance: "behance.net/emmarodriguez",
        photo: "",
      },
      summary: "Innovative creative designer with 6+ years of experience in brand identity, digital design, and user experience. Passionate about creating visually compelling solutions that drive engagement and conversion.",
      portfolio: [
        {
          title: "Brand Identity - TechStart",
          description: "Complete brand identity including logo, color palette, and marketing materials for tech startup.",
          link: "behance.net/project/techstart",
          technologies: "Adobe Creative Suite, Figma"
        },
        {
          title: "E-commerce Website Redesign",
          description: "UI/UX redesign resulting in 40% increase in conversions and improved user experience.",
          link: "dribbble.com/shots/ecommerce",
          technologies: "Figma, Sketch, Principle"
        }
      ],
      skills: [
        "Adobe Creative Suite",
        "Figma",
        "Sketch",
        "UI/UX Design",
        "Brand Identity",
        "Typography",
        "Color Theory",
        "Prototyping",
        "User Research",
        "Design Systems"
      ],
      experience: [
        {
          title: "Senior Creative Designer",
          company: "Design Studio Pro",
          startDate: "Mar 2021",
          endDate: "Present",
          description: "Lead design projects for Fortune 500 clients, manage team of 4 designers, increased client satisfaction by 35% through innovative design solutions."
        },
        {
          title: "Graphic Designer",
          company: "Creative Agency",
          startDate: "Jun 2018",
          endDate: "Feb 2021",
          description: "Created brand identities, marketing materials, and digital assets for 50+ clients across various industries."
        }
      ],
      education: [
        {
          degree: "Bachelor of Fine Arts in Graphic Design",
          institution: "Art Institute of California",
          startDate: "2014",
          endDate: "2018",
          grade: "GPA: 3.8/4.0"
        }
      ],
      awards: [
        { title: "Best Creative Campaign", issuer: "Design Awards 2023", date: "2023" },
        { title: "Rising Star Designer", issuer: "Creative Industry Awards", date: "2022" }
      ],
      languages: ["English (Native)", "Spanish (Fluent)"]
    }
  },

  // Data Scientist - Tech Modern Layout  
  data_scientist: {
    name: "Data Scientist",
    previewImage: "/templates/previews/data_scientist.png",
    category: "Job-Specific",
    layout: {
      type: "tech-modern",
      headerType: "tech-banner",
      sectionsOrder: ["personal", "summary", "skills", "experience", "projects", "education", "publications", "languages", "customSections"],
      sidebarSections: ["personal.photo", "skills", "education"],
      mainSections: ["summary", "experience", "projects", "publications"],
      showIcons: true,
      sidebar: "left",
      sidebarWidth: "33%",
      sectionCard: true,
      sectionDividers: false,
    },
    styles: {
      fontFamily: "'JetBrains Mono', 'Fira Code', monospace",
      fontSize: "10pt",
      lineHeight: "1.6",
      borderRadius: "8px",
      photo: {
        shape: "rounded",
        size: "100px",
        border: "3px solid #7c3aed",
        shadow: "0 4px 16px rgba(124, 58, 237, 0.25)",
      },
      colors: {
        primary: "#111827",
        secondary: "#7c3aed",
        accent: "#a78bfa",
        text: "#1e1b4b",
        background: "#ffffff",
        sidebar: "linear-gradient(135deg, #ede9fe 0%, #ddd6fe 100%)",
        headerGradient: "linear-gradient(135deg, #111827 0%, #7c3aed 100%)",
        cardBg: "#f5f3ff",
        border: "#d8b4fe",
      },
      icons: {
        skills: "🔬",
        experience: "💻",
        projects: "📊",
        education: "🎓",
        publications: "📝"
      }
    },
    defaultData: {
      personal: {
        name: "Alex Chen",
        email: "alex.chen@datascience.com",
        phone: "+1 (555) 345-6789",
        location: "Seattle, WA",
        dateOfBirth: "",
        gender: "",
        maritalStatus: "",
        linkedin: "linkedin.com/in/alexchen",
        github: "github.com/alexchen",
        kaggle: "kaggle.com/alexchen",
        photo: "",
      },
      summary: "Data scientist with 5+ years of experience in machine learning, statistical analysis, and big data processing. Expertise in Python, R, and cloud platforms with proven track record of delivering data-driven solutions.",
      skills: [
        "Python",
        "R",
        "SQL",
        "Machine Learning",
        "Deep Learning",
        "TensorFlow",
        "PyTorch",
        "Pandas",
        "NumPy",
        "Scikit-learn",
        "AWS",
        "Docker",
        "Git",
        "Tableau"
      ],
      experience: [
        {
          title: "Senior Data Scientist",
          company: "Tech Innovations Inc",
          startDate: "Jan 2022",
          endDate: "Present",
          description: "Lead ML model development, improved recommendation system accuracy by 30%, deployed models serving 1M+ users daily using AWS and Docker."
        },
        {
          title: "Data Scientist",
          company: "Analytics Corp",
          startDate: "Jun 2019",
          endDate: "Dec 2021",
          description: "Built predictive models for customer churn, automated data pipelines processing 10TB+ daily, reduced processing time by 60%."
        }
      ],
      projects: [
        {
          title: "Customer Segmentation ML Model",
          description: "Developed unsupervised learning model using K-means clustering to segment 500K+ customers, resulting in 25% increase in marketing ROI.",
          technologies: "Python, Pandas, Scikit-learn, AWS"
        },
        {
          title: "Real-time Fraud Detection System",
          description: "Built real-time fraud detection using ensemble methods and streaming data, achieving 95% accuracy with <100ms latency.",
          technologies: "Python, TensorFlow, Apache Kafka, Docker"
        }
      ],
      education: [
        {
          degree: "Master of Science in Data Science",
          institution: "University of Washington",
          startDate: "2017",
          endDate: "2019",
          grade: "GPA: 3.9/4.0"
        },
        {
          degree: "Bachelor of Science in Computer Science",
          institution: "UC Berkeley",
          startDate: "2013",
          endDate: "2017",
          grade: "Magna Cum Laude"
        }
      ],
      publications: [
        { title: "Ensemble Methods for Large-Scale Classification", journal: "Journal of Machine Learning Research", date: "2023" },
        { title: "Optimizing Deep Learning Models for Production", conference: "NeurIPS 2022", date: "2022" }
      ],
      languages: ["English (Native)", "Mandarin (Native)", "Python (Fluent)"]
    }
  },
};